name: Set up Windows environment
description: Set up everything needed to build and release things on Windows
inputs:
  aws-access-key-id:
    required: false
    description: The aws-access-key-id used to authenticate with AWS
  aws-secret-access-key:
    required: false
    description: The aws-secret-access-key used to authenticate with AWS
  cloudflare-email:
    required: false
    description: The email used to authenticate with Cloudflare
  cloudflare-token:
    required: false
    description: The token used to authenticate with Cloudflare
  architecture:
    description: The target architecture
    default: x64
runs:
  using: composite
  steps:
    - name: Configure git
      run: |
        git config --global user.name "Frida Developers"
        git config --global user.email "oleavr@frida.re"
      shell: pwsh
    - name: Check out releng
      run: |
        git submodule update --init --depth 1 releng
        cd releng
        git submodule update --init --depth 1
      shell: pwsh
    - name: Add convenience environment variables
      run: |
        echo "FRIDA_PREFIX=$Env:RUNNER_WORKSPACE\dist" >> $Env:GITHUB_ENV
        echo "FRIDA_VERSION=$(python releng/frida_version.py)" >> $Env:GITHUB_ENV
      shell: pwsh
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: ${{ inputs.architecture }}
    - name: Install setuptools
      run: pip install setuptools
      shell: pwsh
